### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by Toastrackenigma** [Toastrackenigma/Robotics-Website#2]
Get user login, MySQL, sessions, admin and account creation working.

**Do we want anyone to be able to sign up or just people chosen by admins? Access codes?**

**Comment by Toastrackenigma** [comment]
Thinking about having a list of each member's name which they can click to then type their password and log in - so, chosen by admins.

**Comment by SamGriffen** [comment]
So like when you go to log in? It would have a screen like:

Sam Griffen
Orlando Parisblue
Meme Memerson

Then you click to enter your password?

**Comment by Toastrackenigma** [comment]
Yup, pretty much. And admin can make new users

**Comment by SamGriffen** [comment]
Okay. Does that consider privacy? Do we really want to be exposing names to anyone who wishes to see them?

**Comment by Toastrackenigma** [comment]
Yeah, maybe just do it like a normal login then?

I thought the idea was cool, but didn't really think it through re. privacy :P

**Comment by Toastrackenigma** [comment]
Done, closing.
